version: '3.8'
services:
  oracledb:
    image: gvenzl/oracle-xe:18.4.0-slim
    container_name: oracledb
    environment:
      ORACLE_PASSWORD: ${DB_PASSWORD}
      ORACLE_DATABASE: ${DB_NAME}
      APP_USER: ${DB_USER}
      APP_USER_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "1521:1521"

