spring:
  application:
    name: XPTO

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_USER_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Oracle12cDialect

    flyway:
      enabled: true